const audioFiles =[
    {
        audios:{
        initial_iteration:{audio:'static/music/01ausmei/01ausmei.wav',iteration:'static/music/01ausmei/initial_iteration.wav'},
        iteration1:{audio:'static/music/01ausmei/01ausmei1.wav',iteration:'static/music/01ausmei/iteration1.wav'},
        iteration2:{audio:'static/music/01ausmei/01ausmei2.wav',iteration:'static/music/01ausmei/iteration2.wav'},
        iteration3:{audio:'static/music/01ausmei/01ausmei3.wav',iteration:'static/music/01ausmei/iteration3.wav'}
        }
    },
    {
        audios:{
        initial_iteration:{audio:'static/music/03achgot/03achgot.wav',iteration:'static/music/03achgot/initial_iteration.wav'},
        iteration1:{audio:'static/music/03achgot/03achgot1.wav',iteration:'static/music/03achgot/iteration1.wav'},
        iteration2:{audio:'static/music/03achgot/03achgot2.wav',iteration:'static/music/03achgot/iteration2.wav'},
        iteration3:{audio:'static/music/03achgot/03achgot3.wav',iteration:'static/music/03achgot/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/14oherre/14oherre.wav',iteration:'static/music/14oherre/initial_iteration.wav'},
            iteration1:{audio:'static/music/14oherre/14oherre1.wav',iteration:'static/music/14oherre/iteration1.wav'},
            iteration2:{audio:'static/music/14oherre/14oherre2.wav',iteration:'static/music/14oherre/iteration2.wav'},
            iteration3:{audio:'static/music/14oherre/14oherre3.wav',iteration:'static/music/14oherre/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/15christ/15christ.wav',iteration:'static/music/15christ/initial_iteration.wav'},
            iteration1:{audio:'static/music/15christ/15christ1.wav',iteration:'static/music/15christ/iteration1.wav'},
            iteration2:{audio:'static/music/15christ/15christ2.wav',iteration:'static/music/15christ/iteration2.wav'},
            iteration3:{audio:'static/music/15christ/15christ3.wav',iteration:'static/music/15christ/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/Beth_audio_1/Beth_audio_1.wav',iteration:'static/music/Beth_audio_1/initial_iteration.wav'},
            iteration1:{audio:'static/music/Beth_audio_1/Beth_audio_11.wav',iteration:'static/music/Beth_audio_1/iteration1.wav'},
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/catech1/catech1.wav',iteration:'static/music/catech1/initial_iteration.wav'},
            iteration1:{audio:'static/music/catech1/catech11.wav',iteration:'static/music/catech1/iteration1.wav'},
            iteration2:{audio:'static/music/catech1/catech12.wav',iteration:'static/music/catech1/iteration2.wav'},
            iteration3:{audio:'static/music/catech1/catech13.wav',iteration:'static/music/catech1/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/Choplin_audio_4/Choplin_audio_4.wav',iteration:'static/music/Choplin_audio_4/initial_iteration.wav'},
            iteration1:{audio:'static/music/Choplin_audio_4/Choplin_audio_41.wav',iteration:'static/music/Choplin_audio_4/iteration1.wav'},
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/Choplin_audio_6/Choplin_audio_6.wav',iteration:'static/music/Choplin_audio_6/initial_iteration.wav'},
            iteration1:{audio:'static/music/Choplin_audio_6/Choplin_audio_61.wav',iteration:'static/music/Choplin_audio_6/iteration1.wav'},
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/jazz_audio2/jazz_audio2.wav',iteration:'static/music/jazz_audio2/initial_iteration.wav'},
            iteration1:{audio:'static/music/jazz_audio2/jazz_audio21.wav',iteration:'static/music/jazz_audio2/iteration1.wav'},
            iteration2:{audio:'static/music/jazz_audio2/jazz_audio22.wav',iteration:'static/music/jazz_audio2/iteration2.wav'},
            iteration3:{audio:'static/music/jazz_audio2/jazz_audio23.wav',iteration:'static/music/jazz_audio2/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/jazz_audio4/jazz_audio4.wav',iteration:'static/music/jazz_audio4/initial_iteration.wav'},
            iteration1:{audio:'static/music/jazz_audio4/jazz_audio41.wav',iteration:'static/music/jazz_audio4/iteration1.wav'},
            iteration2:{audio:'static/music/jazz_audio4/jazz_audio42.wav',iteration:'static/music/jazz_audio4/iteration2.wav'},
            iteration3:{audio:'static/music/jazz_audio4/jazz_audio43.wav',iteration:'static/music/jazz_audio4/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/jazz_audio8/jazz_audio8.wav',iteration:'static/music/jazz_audio8/initial_iteration.wav'},
            iteration1:{audio:'static/music/jazz_audio8/jazz_audio81.wav',iteration:'static/music/jazz_audio8/iteration1.wav'},
            iteration2:{audio:'static/music/jazz_audio8/jazz_audio82.wav',iteration:'static/music/jazz_audio8/iteration2.wav'},
            iteration3:{audio:'static/music/jazz_audio8/jazz_audio83.wav',iteration:'static/music/jazz_audio8/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/jazz_audio10/jazz_audio10.wav',iteration:'static/music/jazz_audio10/initial_iteration.wav'},
            iteration1:{audio:'static/music/jazz_audio10/jazz_audio101.wav',iteration:'static/music/jazz_audio10/iteration1.wav'},
            iteration2:{audio:'static/music/jazz_audio10/jazz_audio102.wav',iteration:'static/music/jazz_audio10/iteration2.wav'},
            iteration3:{audio:'static/music/jazz_audio10/jazz_audio103.wav',iteration:'static/music/jazz_audio10/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/jazz_audio17/jazz_audio17.wav',iteration:'static/music/jazz_audio17/initial_iteration.wav'},
            iteration1:{audio:'static/music/jazz_audio17/jazz_audio171.wav',iteration:'static/music/jazz_audio17/iteration1.wav'},
            iteration2:{audio:'static/music/jazz_audio17/jazz_audio172.wav',iteration:'static/music/jazz_audio17/iteration2.wav'},
            iteration3:{audio:'static/music/jazz_audio17/jazz_audio173.wav',iteration:'static/music/jazz_audio17/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/Mozart_audio_3/Mozart_audio_3.wav',iteration:'static/music/Mozart_audio_3/initial_iteration.wav'},
            iteration1:{audio:'static/music/Mozart_audio_3/Mozart_audio_31.wav',iteration:'static/music/Mozart_audio_3/iteration1.wav'},
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/muss_1/muss_1.wav',iteration:'static/music/muss_1/initial_iteration.wav'},
            iteration1:{audio:'static/music/muss_1/muss_11.wav',iteration:'static/music/muss_1/iteration1.wav'},
        }
    },
    {
        audios:{
        initial_iteration:{audio:'static/music/pop_audio4/pop_audio4.wav',iteration:'static/music/pop_audio4/initial_iteration.wav'},
        iteration1:{audio:'static/music/pop_audio4/pop_audio41.wav',iteration:'static/music/pop_audio4/iteration1.wav'},
        iteration2:{audio:'static/music/pop_audio4/pop_audio42.wav',iteration:'static/music/pop_audio4/iteration2.wav'},
        iteration3:{audio:'static/music/pop_audio4/pop_audio43.wav',iteration:'static/music/pop_audio4/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/pop_audio10/pop_audio10.wav',iteration:'static/music/pop_audio10/initial_iteration.wav'},
            iteration1:{audio:'static/music/pop_audio10/pop_audio101.wav',iteration:'static/music/pop_audio10/iteration1.wav'},
            iteration2:{audio:'static/music/pop_audio10/pop_audio102.wav',iteration:'static/music/pop_audio10/iteration2.wav'},
            iteration3:{audio:'static/music/pop_audio10/pop_audio103.wav',iteration:'static/music/pop_audio10/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/pop_audio13/pop_audio13.wav',iteration:'static/music/pop_audio13/initial_iteration.wav'},
            iteration1:{audio:'static/music/pop_audio13/pop_audio131.wav',iteration:'static/music/pop_audio13/iteration1.wav'},
            iteration2:{audio:'static/music/pop_audio13/pop_audio132.wav',iteration:'static/music/pop_audio13/iteration2.wav'},
            iteration3:{audio:'static/music/pop_audio13/pop_audio133.wav',iteration:'static/music/pop_audio13/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/pop_audio16/pop_audio16.wav',iteration:'static/music/pop_audio16/initial_iteration.wav'},
            iteration1:{audio:'static/music/pop_audio16/pop_audio161.wav',iteration:'static/music/pop_audio16/iteration1.wav'},
            iteration2:{audio:'static/music/pop_audio16/pop_audio162.wav',iteration:'static/music/pop_audio16/iteration2.wav'},
            iteration3:{audio:'static/music/pop_audio16/pop_audio163.wav',iteration:'static/music/pop_audio16/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/pop_audio23/pop_audio23.wav',iteration:'static/music/pop_audio23/initial_iteration.wav'},
            iteration1:{audio:'static/music/pop_audio23/pop_audio231.wav',iteration:'static/music/pop_audio23/iteration1.wav'},
            iteration2:{audio:'static/music/pop_audio23/pop_audio232.wav',iteration:'static/music/pop_audio23/iteration2.wav'},
            iteration3:{audio:'static/music/pop_audio23/pop_audio233.wav',iteration:'static/music/pop_audio23/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/pop_audio30/pop_audio30.wav',iteration:'static/music/pop_audio30/initial_iteration.wav'},
            iteration1:{audio:'static/music/pop_audio30/pop_audio301.wav',iteration:'static/music/pop_audio30/iteration1.wav'},
            iteration2:{audio:'static/music/pop_audio30/pop_audio302.wav',iteration:'static/music/pop_audio30/iteration2.wav'},
            iteration3:{audio:'static/music/pop_audio30/pop_audio303.wav',iteration:'static/music/pop_audio30/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/Schubert_audio_2/Schubert_audio_2.wav',iteration:'static/music/Schubert_audio_2/initial_iteration.wav'},
            iteration1:{audio:'static/music/Schubert_audio_2/Schubert_audio_21.wav',iteration:'static/music/Schubert_audio_2/iteration1.wav'},
        }
    }, {
        audios:{
            initial_iteration:{audio:'static/music/09ermunt/09ermunt.wav',iteration:'static/music/09ermunt/initial_iteration.wav'},
            iteration1:{audio:'static/music/09ermunt/09ermunt1.wav',iteration:'static/music/09ermunt/iteration1.wav'},
            iteration2:{audio:'static/music/09ermunt/09ermunt2.wav',iteration:'static/music/09ermunt/iteration2.wav'},
            iteration3:{audio:'static/music/09ermunt/09ermunt3.wav',iteration:'static/music/09ermunt/iteration3.wav'}
        }
    },
    {
        audios:{
            initial_iteration:{audio:'static/music/jazz_audio1/jazz_audio1.wav',iteration:'static/music/jazz_audio1/initial_iteration.wav'},
            iteration1:{audio:'static/music/jazz_audio1/jazz_audio11.wav',iteration:'static/music/jazz_audio1/iteration1.wav'},
            iteration2:{audio:'static/music/jazz_audio1/jazz_audio12.wav',iteration:'static/music/jazz_audio1/iteration2.wav'},
            iteration3:{audio:'static/music/jazz_audio1/jazz_audio13.wav',iteration:'static/music/jazz_audio1/iteration3.wav'}
        }
    },
    
    

]

